/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Col1Layout: typeof import('./src/components/Col1Layout.vue')['default']
    Col2Layout: typeof import('./src/components/Col2Layout.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    IconMenuBox: typeof import('./src/components/IconMenuBox.vue')['default']
    IECControlBox: typeof import('./src/components/ImageEditCard/components/IECControlBox.vue')['default']
    IECPostList: typeof import('./src/components/ImageEditCard/components/IECPostList.vue')['default']
    ImageEditCard: typeof import('./src/components/ImageEditCard/ImageEditCard.vue')['default']
    ImageEditDialog: typeof import('./src/components/ImageEditDialog.vue')['default']
    ImageGroup: typeof import('./src/components/ImageGroup.vue')['default']
    ImageSelector: typeof import('./src/components/ImageSelector.vue')['default']
    ImageUploader: typeof import('./src/components/ImageUploader.vue')['default']
    LinkGroup: typeof import('./src/components/LinkGroup.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    PostDeleteDialog: typeof import('./src/components/PostDeleteDialog.vue')['default']
    PostGroup: typeof import('./src/components/PostGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SakiEmpty: typeof import('./src/components/SakiEmpty.vue')['default']
    TestBox: typeof import('./src/components/TestBox.vue')['default']
    TextWithLink: typeof import('./src/components/TextWithLink.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
